param dir symbolic := "/home/vito/Scrivania/Optimization-of-a-Robot-delivery/analisi/";
# ---------------------------------------------------------------------------
# 1. SENSITIVITA CAPACITA BATTERIA
# ---------------------------------------------------------------------------
param res_cap_val       {1..20};
param res_cap_costo     {1..20};
param res_cap_energia   {1..20};
param res_cap_tempo     {1..20};
param res_cap_ritardo   {1..20};
param res_cap_penale    {1..20};
param res_cap_obiettivo {1..20};
param res_cap_consegn   {1..20};
param res_cap_archi     {1..20};
param res_cap_status    {1..20} symbolic;
param idx_cap default 1;

print "";
print "===============================================================";
print "   SENSITIVITA: CAPACITA BATTERIA";
print "===============================================================";
let idx_cap := 1;

for {c_val in {10, 40, 70 ,100, 200 ,400, 600, 1000, 1100, 1260,1300, 1400, 1500, 1600, 1700, 1800, 1900, 2000, 2100, 2200}} {
    let cap_batteria := c_val;
    solve;
    
    let res_cap_val[idx_cap]       := c_val;
    let res_cap_status[idx_cap]    := solve_result;
    let res_cap_archi[idx_cap]     := sum {(i,j) in A} x[i,j];
    let res_cap_costo[idx_cap]     := sum {(i,j) in A} costo[i,j]            * x[i,j];
    let res_cap_energia[idx_cap]   := sum {(i,j) in A} energia[i,j]          * x[i,j];
    let res_cap_tempo[idx_cap]     := sum {(i,j) in A} tempoPercorrenza[i,j] * x[i,j];
    let res_cap_ritardo[idx_cap]   := sum {cc in C} ritardo[cc];
    let res_cap_penale[idx_cap]    := sum {p in P} penale_mancata_consegna[p] * (1 - consegnato[p]);
    let res_cap_obiettivo[idx_cap] := CostoTotale;
    let res_cap_consegn[idx_cap]   := sum {p in P} consegnato[p];
    
    printf "CAP=%4d | %-12s | Archi=%2d | Viaggio=%7.2f | Energia=%7.2f | Tempo=%7.2f | Ritardo=%6.2f | Penale=%7.2f | Obj=%.4f | Consegnati=%d/%d\n",
           c_val, solve_result,
           res_cap_archi[idx_cap],
           res_cap_costo[idx_cap], res_cap_energia[idx_cap], res_cap_tempo[idx_cap],
           res_cap_ritardo[idx_cap], res_cap_penale[idx_cap],
           res_cap_obiettivo[idx_cap],
           res_cap_consegn[idx_cap], card(P);
           
    let idx_cap := idx_cap + 1;
}

param code_status_cap {1..20};
for {k in 1..20} {
    let code_status_cap[k] :=
        if res_cap_status[k] == "solved"     then 0
        else if res_cap_status[k] == "infeasible" then 1
        else 9;
}

# Sensitività batteria
printf "# cap_val status_code n_archi costo energia tempo ritardo penale obiettivo consegnati\n"
    > (dir & "out_sens_batteria.txt");
for {k in 1..20} {
    printf "%f %d %d %f %f %f %f %f %f %d\n",
        res_cap_val[k], code_status_cap[k], res_cap_archi[k],
        res_cap_costo[k], res_cap_energia[k], res_cap_tempo[k],
        res_cap_ritardo[k], res_cap_penale[k],
        res_cap_obiettivo[k], res_cap_consegn[k]
        > (dir & "out_sens_batteria.txt");
}
close (dir & "out_sens_batteria.txt");